"""
Generate starter analysis code from a catalogue match.

The skeleton is a fixed template and the parameters come from the card, so the
disclosure rules are structural rather than advisory: suppression happens
before any value is returned, the unit of analysis is stated in the docstring
and echoed in the result, and nothing per-record is ever printed.

A model may adapt what these produce. It does not produce them.
"""
from __future__ import annotations

import os
from string import Template
from typing import Dict, List, Optional

from sdk.card import Card
from sdk.catalogue import Match

ANALYSES_DIR = "analyses"


class SnippetError(Exception):
    """Raised when a snippet cannot be generated for the given card."""


def accessor(path: str) -> str:
    """Attribute access for a leaf path against the generated models."""
    return "record." + path


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in text).strip("_").lower()


_HEADER = '''"""$title

$summary

Generated by epsilon copilot from card $card_ref.
UNIT OF ANALYSIS: $unit. $unit_note
$caveat_block"""
from collections import Counter, defaultdict

from generated.models import create_dataset

MIN_CELL = $min_cell  # suppression threshold from the dataset card

'''

_SUPPRESS = '''
def _suppress(counts):
    """Replace any count below the disclosure threshold with None."""
    return dict((k, (v if v >= MIN_CELL else None)) for k, v in counts.items())

'''

_TEMPLATES: Dict[str, str] = {}

_TEMPLATES["describe"] = '''
def main():
    dataset = create_dataset()

    totals = defaultdict(Counter)
    numeric = defaultdict(list)

    for record in dataset:
$describe_body
    summary = {"unit": "$unit", "n_rows": len(dataset), "fields": {}}

    for field, counts in totals.items():
        summary["fields"][field] = {
            "distinct": len(counts),
            "counts": _suppress(counts),
        }
    for field, values in numeric.items():
        clean = [v for v in values if v is not None]
        if len(clean) < MIN_CELL:
            summary["fields"][field] = {"suppressed": True}
            continue
        clean.sort()
        summary["fields"][field] = {
            "n": len(clean),
            "min": clean[0],
            "max": clean[-1],
            "mean": round(sum(clean) / float(len(clean)), 2),
            "median": clean[len(clean) // 2],
        }

    return summary


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["composition"] = '''
def main():
    dataset = create_dataset()

    counts = Counter()
    for record in dataset:
        stratum = $by_expr or "UNKNOWN"
        outcome = $outcome_expr or "UNKNOWN"
        counts[(str(stratum), str(outcome))] += 1

    # Denominator per stratum, so shares are within-group and not of the whole.
    totals = Counter()
    for (stratum, _outcome), n in counts.items():
        totals[stratum] += n

    rows = []
    for (stratum, outcome), n in sorted(counts.items()):
        rows.append({
            "$by_name": stratum,
            "$outcome_name": outcome,
            "n": n if n >= MIN_CELL else None,
            "share_of_stratum": (round(n / float(totals[stratum]), 4)
                                 if n >= MIN_CELL and totals[stratum] else None),
        })

    return {"unit": "$unit", "n_rows": len(dataset), "table": rows}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["cross_tab"] = '''
def main():
    dataset = create_dataset()

    counts = Counter()
    row_totals, col_totals = Counter(), Counter()
    for record in dataset:
        r = str($rows_expr or "UNKNOWN")
        c = str($cols_expr or "UNKNOWN")
        counts[(r, c)] += 1
        row_totals[r] += 1
        col_totals[c] += 1

    n = sum(counts.values())

    # Pearson chi-square. Reported only if every expected count reaches 5;
    # below that the statistic is not interpretable.
    chi2, min_expected, cells = 0.0, None, 0
    for r in row_totals:
        for c in col_totals:
            expected = row_totals[r] * col_totals[c] / float(n) if n else 0.0
            observed = counts.get((r, c), 0)
            if expected > 0:
                chi2 += (observed - expected) ** 2 / expected
            min_expected = expected if min_expected is None else min(min_expected, expected)
            cells += 1

    dof = (len(row_totals) - 1) * (len(col_totals) - 1)
    interpretable = min_expected is not None and min_expected >= 5

    table = []
    for r in sorted(row_totals):
        for c in sorted(col_totals):
            observed = counts.get((r, c), 0)
            table.append({
                "$rows_name": r,
                "$cols_name": c,
                "n": observed if observed >= MIN_CELL else None,
            })

    return {
        "unit": "$unit",
        "n_rows": n,
        "table": table,
        "chi2": round(chi2, 3) if interpretable else None,
        "dof": dof if interpretable else None,
        "note": (None if interpretable else
                 "chi-square withheld: smallest expected count is below 5"),
    }


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["prevalence"] = '''
def main():
    dataset = create_dataset()

    # Grain is $unit, so collapse to one observation per entity before
    # counting. Without this the result is weighted by rows, not entities.
    entities = {}
    for record in dataset:
        key = $dedupe_expr
        if key is None:
            continue
        has = entities.get(key, False)
        entities[key] = has or ($outcome_expr in POSITIVE)

    n = len(entities)
    positive = sum(1 for v in entities.values() if v)

    if n < MIN_CELL or positive < MIN_CELL:
        return {"unit": "entity", "suppressed": True}

    return {
        "unit": "entity",
        "n_entities": n,
        "n_positive": positive,
        "prevalence": round(positive / float(n), 4),
    }


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["group_compare"] = '''
def main():
    dataset = create_dataset()

    groups = defaultdict(list)
    for record in dataset:
        group = $group_expr
        raw = $value_expr
        if group is None or raw is None:
            continue
        try:
            groups[str(group)].append(float(raw))
        except (TypeError, ValueError):
            continue

    out = {"unit": "$unit", "groups": {}}
    for name, values in sorted(groups.items()):
        if len(values) < MIN_CELL:
            out["groups"][name] = {"suppressed": True}
            continue
        values.sort()
        mean = sum(values) / float(len(values))
        variance = sum((v - mean) ** 2 for v in values) / float(len(values) - 1)
        out["groups"][name] = {
            "n": len(values),
            "mean": round(mean, 3),
            "sd": round(variance ** 0.5, 3),
            "median": values[len(values) // 2],
        }

    return out


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["logistic"] = '''
def main():
    dataset = create_dataset()

    # Covariates are reported as stratified outcome rates rather than fitted
    # coefficients: a model fit belongs in a library, and the released table
    # should carry the counts a reviewer needs to check suppression.
    strata = defaultdict(Counter)
    for record in dataset:
        outcome = "positive" if $outcome_expr in POSITIVE else "negative"
$logistic_body
    rows = []
    for (field, level), counts in sorted(strata.items()):
        total = sum(counts.values())
        positive = counts.get("positive", 0)
        rows.append({
            "covariate": field,
            "level": level,
            "n": total if total >= MIN_CELL else None,
            "rate": (round(positive / float(total), 4)
                     if total >= MIN_CELL and positive >= MIN_CELL else None),
        })

    return {"unit": "$unit", "outcome": "$outcome_name", "strata": rows}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["trend"] = '''
def main():
    dataset = create_dataset()

    buckets = Counter()
    for record in dataset:
        raw = $time_expr
        if raw is None:
            continue
        bucket = str(raw)[:$bucket_width]  # $bucket_note
        buckets[bucket] += 1

    series = []
    for bucket in sorted(buckets):
        n = buckets[bucket]
        series.append({"period": bucket, "n": n if n >= MIN_CELL else None})

    return {"unit": "$unit", "bucket": "$bucket_label", "series": series}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["survival"] = '''
def main():
    dataset = create_dataset()

    # One observation per entity: a survival curve over repeated rows of the
    # same entity is not a survival curve.
    observations = {}
    for record in dataset:
        key = $dedupe_expr
        if key is None:
            continue
        duration = _number($duration_expr)
        if duration is None:
            continue
        event = $event_expr in POSITIVE
        prior = observations.get(key)
        # Keep the earliest event, or the longest follow-up if never observed.
        if prior is None:
            observations[key] = (duration, event)
        elif event and not prior[1]:
            observations[key] = (duration, True)
        elif event == prior[1]:
            observations[key] = (min(duration, prior[0]) if event
                                 else max(duration, prior[0]), event)

    if len(observations) < MIN_CELL:
        return {"unit": "entity", "suppressed": True}

    # Kaplan-Meier: at each distinct event time, multiply the surviving
    # fraction by (1 - deaths / at_risk). Censored entities leave the risk set
    # without contributing an event.
    rows = sorted(observations.values())
    times = sorted(set(t for t, e in rows if e))
    at_risk = len(rows)
    survival, curve = 1.0, []
    consumed = 0
    for t in times:
        at_risk = sum(1 for d, _e in rows if d >= t)
        events = sum(1 for d, e in rows if e and d == t)
        if at_risk <= 0:
            break
        survival *= (1.0 - events / float(at_risk))
        consumed += events
        curve.append({
            "time": t,
            "at_risk": at_risk if at_risk >= MIN_CELL else None,
            "events": events if events >= MIN_CELL else None,
            "survival": round(survival, 4),
        })

    return {
        "unit": "entity",
        "n_entities": len(rows),
        "n_events": sum(1 for _d, e in rows if e),
        "curve": curve,
    }


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_BUCKET_WIDTH = {"year": (4, "YYYY"), "quarter": (7, "YYYY-MM, map to quarter"),
                 "month": (7, "YYYY-MM"), "day": (10, "YYYY-MM-DD")}


def _unit_note(card: Card, match: Match) -> str:
    if match.unit == "entity":
        return "Rows are collapsed per entity before anything is counted."
    if not card.has_dedupe_key and card.grain.known:
        return ("This archetype has no entity key, so results describe {0}s "
                "and not entities. Report that denominator.".format(card.grain.label))
    return "Report this denominator in your methods."


def _caveat_block(match: Match) -> str:
    if not match.warnings:
        return ""
    lines = ["", "Card warnings that apply to this analysis:"]
    for warning in match.warnings:
        lines.append("  - " + warning)
    lines.append("")
    return "\n".join(lines)


def _describe_body(card: Card) -> str:
    lines = []
    for leaf in card.all_leaves():
        expr = accessor(leaf.path)
        if leaf.is_numeric:
            lines.append('        numeric["{0}"].append(_number({1}))'.format(leaf.path, expr))
        else:
            lines.append('        totals["{0}"][str({1})] += 1'.format(leaf.path, expr))
    lines.append("")
    return "\n".join(lines)


def _logistic_body(covariates: List[str]) -> str:
    lines = []
    for path in covariates:
        lines.append('        strata[("{0}", str({1}))][outcome] += 1'.format(path, accessor(path)))
    lines.append("")
    return "\n".join(lines)


_NUMBER_HELPER = '''
def _number(value):
    """Coerce a CSV field to a number, or None when it is not one."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return None

'''


def render(card: Card, match: Match) -> str:
    """Render the analysis code for a feasible match."""
    if not match.feasible:
        raise SnippetError(
            "{0} is not feasible for this dataset: {1}".format(
                match.key, match.blockers[0] if match.blockers else "unknown reason"))
    template = _TEMPLATES.get(match.key)
    if template is None:
        raise SnippetError("no template for analysis '{0}'".format(match.key))

    card_ref = card.schema_hash[:12] if card.schema_hash else (card.archetype_id or "unknown")
    values = {
        "title": match.title,
        "summary": match.summary,
        "unit": match.unit,
        "unit_note": _unit_note(card, match),
        "caveat_block": _caveat_block(match),
        "card_ref": card_ref,
        "min_cell": str(card.policy.min_cell),
    }

    body = _HEADER
    params = match.params

    if match.key == "describe":
        body += _NUMBER_HELPER + _SUPPRESS
        values["describe_body"] = _describe_body(card)
    elif match.key == "composition":
        values["outcome_expr"] = accessor(params["outcome"])
        values["by_expr"] = accessor(params["by"])
        values["outcome_name"] = _slug(params["outcome"])
        values["by_name"] = _slug(params["by"])
    elif match.key == "cross_tab":
        values["rows_expr"] = accessor(params["rows"])
        values["cols_expr"] = accessor(params["cols"])
        values["rows_name"] = _slug(params["rows"])
        values["cols_name"] = _slug(params["cols"])
    elif match.key == "prevalence":
        if not card.grain.dedupe_key:
            raise SnippetError("prevalence requires a dedupe key")
        body = body.replace("MIN_CELL = $min_cell", 'POSITIVE = set()  # fill in the values that count as positive\nMIN_CELL = $min_cell')
        values["dedupe_expr"] = accessor(card.grain.dedupe_key)
        values["outcome_expr"] = accessor(params["outcome"])
    elif match.key == "group_compare":
        values["value_expr"] = accessor(params["value"])
        values["group_expr"] = accessor(params["group"])
    elif match.key == "logistic":
        body = body.replace("MIN_CELL = $min_cell", 'POSITIVE = set()  # fill in the values that count as positive\nMIN_CELL = $min_cell')
        covariates = [c.strip() for c in params.get("covariates", "").split(",") if c.strip()]
        values["outcome_expr"] = accessor(params["outcome"])
        values["outcome_name"] = params["outcome"]
        values["logistic_body"] = _logistic_body(covariates)
    elif match.key == "survival":
        if not card.grain.dedupe_key:
            raise SnippetError("survival requires a dedupe key")
        body = body.replace("MIN_CELL = $min_cell", 'POSITIVE = set()  # fill in the values that count as an event\nMIN_CELL = $min_cell')
        body += _NUMBER_HELPER
        values["dedupe_expr"] = accessor(card.grain.dedupe_key)
        values["duration_expr"] = accessor(params["duration"])
        values["event_expr"] = accessor(params["event"])
    elif match.key == "trend":
        bucket = (params.get("buckets") or "year").split(",")[0].strip()
        width, note = _BUCKET_WIDTH.get(bucket, _BUCKET_WIDTH["year"])
        values["time_expr"] = accessor(params["time"])
        values["bucket_width"] = str(width)
        values["bucket_note"] = note
        values["bucket_label"] = bucket

    return Template(body + template).safe_substitute(values)


def write(card: Card, match: Match, project_dir: str = ".",
          filename: Optional[str] = None) -> str:
    """Render a snippet and write it under analyses/. Returns the path."""
    code = render(card, match)
    directory = os.path.join(project_dir, ANALYSES_DIR)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    init_path = os.path.join(directory, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w", encoding="utf-8") as fh:
            fh.write("")
    path = os.path.join(directory, filename or "{0}.py".format(match.key))
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(code)
    return path
