"""
Generate starter analysis code from a catalogue match.

The skeleton is a fixed template and the parameters come from the profile, so the
disclosure rules are structural rather than advisory: suppression happens
before any value is returned, the unit of analysis is stated in the docstring
and echoed in the result, and nothing per-record is ever printed.

A model may adapt what these produce. It does not produce them.
"""
from __future__ import annotations

import os
from string import Template
from typing import Dict, List, Optional

from sdk.profile import Profile
from sdk.catalogue import Match

ANALYSES_DIR = "analyses"
CHART_HELPER_NAME = "_charts.py"

# Which analyses can be drawn, and which part of their result to draw.
CHARTABLE = {
    "describe": ("fields", "Distribution of {field}"),
    "composition": ("table", "Composition by {by}"),
    "cross_tab": ("table", "{rows} by {cols}"),
    "prevalence": (None, None),
    "trend": ("series", "Trend over time"),
}


class SnippetError(Exception):
    """Raised when a snippet cannot be generated for the given profile."""


def accessor(path: str) -> str:
    """Attribute access for a leaf path against the generated models."""
    return "record." + path


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() else "_" for c in text).strip("_").lower()


_HEADER = '''"""$title

$summary

Generated by epsilon copilot from profile $card_ref.
UNIT OF ANALYSIS: $unit. $unit_note
$caveat_block"""
from collections import Counter, defaultdict

from generated.models import create_dataset

MIN_CELL = $min_cell  # suppression threshold from the dataset profile

'''

_SUPPRESS = '''
# A field with hundreds of levels must not be reported level by level: the tail
# is unreleasable and the head is what a reader needs.
TOP_LEVELS = 15


def _levels(counts):
    """The largest levels that clear the threshold, and how many were held."""
    kept = [(v, n) for v, n in counts.most_common(TOP_LEVELS) if n >= MIN_CELL]
    return {
        "top": [{"value": v, "n": n} for v, n in kept],
        "levels_not_shown": len(counts) - len(kept),
    }


def _bucket(value, width):
    """Coarsen a timestamp to the resolution the profile says is releasable."""
    if value is None:
        return "UNKNOWN"
    return str(value)[:width] or "UNKNOWN"

'''

_TEMPLATES: Dict[str, str] = {}

_TEMPLATES["describe"] = '''
def main():
    dataset = create_dataset()

    totals = defaultdict(Counter)
    numeric = defaultdict(list)

    for record in dataset:
$describe_body
    summary = {"unit": "$unit", "n_rows": len(dataset), "fields": {}}

    for field, counts in totals.items():
        entry = {"distinct": len(counts)}
        entry.update(_levels(counts))
        summary["fields"][field] = entry
    for field, values in numeric.items():
        clean = [v for v in values if v is not None]
        if len(clean) < MIN_CELL:
            summary["fields"][field] = {"suppressed": True}
            continue
        clean.sort()
        summary["fields"][field] = {
            "n": len(clean),
            "min": clean[0],
            "max": clean[-1],
            "mean": round(sum(clean) / float(len(clean)), 2),
            "median": clean[len(clean) // 2],
        }

    return summary


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["composition"] = '''
def main():
    dataset = create_dataset()

    counts = Counter()
    for record in dataset:
        stratum = $by_expr or "UNKNOWN"
        outcome = $outcome_expr or "UNKNOWN"
        counts[(str(stratum), str(outcome))] += 1

    # Denominator per stratum, so shares are within-group and not of the whole.
    totals = Counter()
    for (stratum, _outcome), n in counts.items():
        totals[stratum] += n

    rows = []
    for (stratum, outcome), n in sorted(counts.items()):
        rows.append({
            "$by_name": stratum,
            "$outcome_name": outcome,
            "n": n if n >= MIN_CELL else None,
            "share_of_stratum": (round(n / float(totals[stratum]), 4)
                                 if n >= MIN_CELL and totals[stratum] else None),
        })

    return {"unit": "$unit", "n_rows": len(dataset), "table": rows}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["cross_tab"] = '''
def main():
    dataset = create_dataset()

    counts = Counter()
    row_totals, col_totals = Counter(), Counter()
    for record in dataset:
        r = str($rows_expr or "UNKNOWN")
        c = str($cols_expr or "UNKNOWN")
        counts[(r, c)] += 1
        row_totals[r] += 1
        col_totals[c] += 1

    n = sum(counts.values())

    # Pearson chi-square. Reported only if every expected count reaches 5;
    # below that the statistic is not interpretable.
    chi2, min_expected, cells = 0.0, None, 0
    for r in row_totals:
        for c in col_totals:
            expected = row_totals[r] * col_totals[c] / float(n) if n else 0.0
            observed = counts.get((r, c), 0)
            if expected > 0:
                chi2 += (observed - expected) ** 2 / expected
            min_expected = expected if min_expected is None else min(min_expected, expected)
            cells += 1

    dof = (len(row_totals) - 1) * (len(col_totals) - 1)
    interpretable = min_expected is not None and min_expected >= 5

    table = []
    for r in sorted(row_totals):
        for c in sorted(col_totals):
            observed = counts.get((r, c), 0)
            table.append({
                "$rows_name": r,
                "$cols_name": c,
                "n": observed if observed >= MIN_CELL else None,
            })

    return {
        "unit": "$unit",
        "n_rows": n,
        "table": table,
        "chi2": round(chi2, 3) if interpretable else None,
        "dof": dof if interpretable else None,
        "note": (None if interpretable else
                 "chi-square withheld: smallest expected count is below 5"),
    }


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["prevalence"] = '''
def main():
    dataset = create_dataset()

    # Grain is $unit, so collapse to one observation per entity before
    # counting. Without this the result is weighted by rows, not entities.
    entities = {}
    for record in dataset:
        key = $dedupe_expr
        if key is None:
            continue
        has = entities.get(key, False)
        entities[key] = has or ($outcome_expr in POSITIVE)

    n = len(entities)
    positive = sum(1 for v in entities.values() if v)

    if n < MIN_CELL or positive < MIN_CELL:
        return {"unit": "entity", "suppressed": True}

    return {
        "unit": "entity",
        "n_entities": n,
        "n_positive": positive,
        "prevalence": round(positive / float(n), 4),
    }


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["group_compare"] = '''
def main():
    dataset = create_dataset()

    groups = defaultdict(list)
    for record in dataset:
        group = $group_expr
        raw = $value_expr
        if group is None or raw is None:
            continue
        try:
            groups[str(group)].append(float(raw))
        except (TypeError, ValueError):
            continue

    out = {"unit": "$unit", "groups": {}}
    for name, values in sorted(groups.items()):
        if len(values) < MIN_CELL:
            out["groups"][name] = {"suppressed": True}
            continue
        values.sort()
        mean = sum(values) / float(len(values))
        variance = sum((v - mean) ** 2 for v in values) / float(len(values) - 1)
        out["groups"][name] = {
            "n": len(values),
            "mean": round(mean, 3),
            "sd": round(variance ** 0.5, 3),
            "median": values[len(values) // 2],
        }

    return out


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["logistic"] = '''
def main():
    dataset = create_dataset()

    # Covariates are reported as stratified outcome rates rather than fitted
    # coefficients: a model fit belongs in a library, and the released table
    # should carry the counts a reviewer needs to check suppression.
    strata = defaultdict(Counter)
    for record in dataset:
        outcome = "positive" if $outcome_expr in POSITIVE else "negative"
$logistic_body
    rows = []
    for (field, level), counts in sorted(strata.items()):
        total = sum(counts.values())
        positive = counts.get("positive", 0)
        rows.append({
            "covariate": field,
            "level": level,
            "n": total if total >= MIN_CELL else None,
            "rate": (round(positive / float(total), 4)
                     if total >= MIN_CELL and positive >= MIN_CELL else None),
        })

    return {"unit": "$unit", "outcome": "$outcome_name", "strata": rows}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

_TEMPLATES["trend"] = '''
def main():
    dataset = create_dataset()

    buckets = Counter()
    for record in dataset:
        raw = $time_expr
        if raw is None:
            continue
        bucket = str(raw)[:$bucket_width]  # $bucket_note
        buckets[bucket] += 1

    series = []
    for bucket in sorted(buckets):
        n = buckets[bucket]
        series.append({"period": bucket, "n": n if n >= MIN_CELL else None})

    return {"unit": "$unit", "bucket": "$bucket_label", "series": series}


if __name__ == "__main__":
    import json
    print(json.dumps(main(), indent=2, default=str))
'''

# Written to analyses/_charts.py the first time a chart snippet is generated.
# Stdlib only and deliberately so: the enclave's requirements carry no plotting
# library, and an SVG is text a reviewer can read, unlike a PNG.
CHART_MODULE = '''"""Minimal SVG charts for disclosure-safe output.

Charts are output artifacts. These render from an already-suppressed aggregate
-- a value of None means the cell was below the threshold and is drawn as a
suppressed marker, never as a height. Nothing here touches a record.

Generated by epsilon copilot. Stdlib only; safe to edit.
"""

BAR_HEIGHT = 22
BAR_GAP = 8
LEFT = 190
RIGHT = 70
TOP = 44
PAD = 16

# Chosen to stay legible on a white or a dark background.
INK = "#2b3a36"
MUTED = "#7c8c87"
ACCENT = "#0d6b60"
SUPPRESSED = "#c2cdc9"


def _escape(text):
    return (str(text).replace("&", "&amp;").replace("<", "&lt;")
            .replace(">", "&gt;").replace('"', "&quot;"))


def bar_chart(title, rows, width=720, note=None):
    """Render (label, value) pairs as a horizontal bar chart.

    `value` may be None, meaning the count was suppressed; such rows are drawn
    as a marker with no length so a suppressed cell can never be read back off
    the axis.
    """
    rows = list(rows)
    if not rows:
        return _empty(title, width, "no rows to plot")

    shown = [v for _label, v in rows if v is not None]
    top = max(shown) if shown else 0
    plot = max(width - LEFT - RIGHT, 60)
    height = TOP + len(rows) * (BAR_HEIGHT + BAR_GAP) + PAD + (20 if note else 0)

    out = [
        \'<svg xmlns="http://www.w3.org/2000/svg" width="{0}" height="{1}" \'
        \'viewBox="0 0 {0} {1}" font-family="ui-sans-serif, system-ui, sans-serif">\'
        .format(width, height),
        \'<text x="{0}" y="24" font-size="14" font-weight="600" fill="{1}">{2}</text>\'
        .format(PAD, INK, _escape(title)),
    ]

    y = TOP
    for label, value in rows:
        out.append(
            \'<text x="{0}" y="{1}" font-size="12" fill="{2}" \'
            \'text-anchor="end">{3}</text>\'.format(
                LEFT - 10, y + BAR_HEIGHT - 6, MUTED, _escape(label)[:32]))
        if value is None:
            out.append(
                \'<rect x="{0}" y="{1}" width="26" height="{2}" rx="2" \'
                \'fill="{3}"/>\'.format(LEFT, y, BAR_HEIGHT, SUPPRESSED))
            out.append(
                \'<text x="{0}" y="{1}" font-size="11" fill="{2}">suppressed</text>\'
                .format(LEFT + 34, y + BAR_HEIGHT - 6, MUTED))
        else:
            length = int(plot * (float(value) / top)) if top else 0
            out.append(
                \'<rect x="{0}" y="{1}" width="{2}" height="{3}" rx="2" \'
                \'fill="{4}"/>\'.format(LEFT, y, max(length, 1), BAR_HEIGHT, ACCENT))
            out.append(
                \'<text x="{0}" y="{1}" font-size="11" fill="{2}">{3:,}</text>\'
                .format(LEFT + length + 8, y + BAR_HEIGHT - 6, INK, value))
        y += BAR_HEIGHT + BAR_GAP

    if note:
        out.append(
            \'<text x="{0}" y="{1}" font-size="11" fill="{2}">{3}</text>\'
            .format(PAD, height - 8, MUTED, _escape(note)))
    out.append("</svg>")
    return "\\n".join(out)


def _empty(title, width, message):
    return (\'<svg xmlns="http://www.w3.org/2000/svg" width="{0}" height="80">\'
            \'<text x="16" y="30" font-size="14">{1}</text>\'
            \'<text x="16" y="54" font-size="12" fill="{2}">{3}</text></svg>\'
            ).format(width, _escape(title), MUTED, _escape(message))


def write_chart(path, svg):
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(svg)
    return path
'''


_CHART_SECTIONS = {}

_CHART_SECTIONS["cross_tab"] = '''

def chart(result=None):
    """Draw the released table. Suppressed cells are drawn as suppressed."""
    result = result or main()
    rows = [("{0} / {1}".format(r["$rows_name"], r["$cols_name"]), r["n"])
            for r in result["table"]]
    svg = bar_chart("$chart_title", rows,
                    note="unit: {0}; synthetic data".format(result["unit"]))
    return write_chart("$chart_path", svg)
'''

_CHART_SECTIONS["composition"] = '''

def chart(result=None):
    """Draw the released table. Suppressed cells are drawn as suppressed."""
    result = result or main()
    rows = [("{0} / {1}".format(r["$by_name"], r["$outcome_name"]), r["n"])
            for r in result["table"]]
    svg = bar_chart("$chart_title", rows,
                    note="unit: {0}; synthetic data".format(result["unit"]))
    return write_chart("$chart_path", svg)
'''

_CHART_SECTIONS["trend"] = '''

def chart(result=None):
    """Draw the released series. Suppressed periods are drawn as suppressed."""
    result = result or main()
    rows = [(r["period"], r["n"]) for r in result["series"]]
    svg = bar_chart("$chart_title", rows,
                    note="bucket: {0}; synthetic data".format(result["bucket"]))
    return write_chart("$chart_path", svg)
'''

_CHART_SECTIONS["describe"] = '''

def chart(field=None, result=None):
    """Draw one field's released levels. Pass a field path to choose it."""
    result = result or main()
    fields = result["fields"]
    field = field or sorted(k for k, v in fields.items() if "top" in v)[0]
    entry = fields[field]
    rows = [(level["value"], level["n"]) for level in entry.get("top", [])]
    hidden = entry.get("levels_not_shown", 0)
    svg = bar_chart("Distribution of " + field, rows,
                    note="{0} further level(s) below the threshold; "
                         "synthetic data".format(hidden))
    return write_chart("$chart_path", svg)
'''

_CHART_IMPORT = "from analyses._charts import bar_chart, write_chart\n"


_BUCKET_WIDTH = {"year": (4, "YYYY"), "quarter": (7, "YYYY-MM, map to quarter"),
                 "month": (7, "YYYY-MM"), "day": (10, "YYYY-MM-DD")}


def _unit_note(profile: Profile, match: Match) -> str:
    if match.unit == "entity":
        return "Rows are collapsed per entity before anything is counted."
    if not profile.has_dedupe_key:
        return ("This archetype has no entity key, so results describe {0}s "
                "and not entities. Report that denominator.".format(profile.grain.label))
    return "Report this denominator in your methods."


def _caveat_block(match: Match) -> str:
    if not match.warnings:
        return ""
    lines = ["", "Measured warnings that apply to this analysis:"]
    for warning in match.warnings:
        lines.append("  - " + warning)
    lines.append("")
    return "\n".join(lines)


# How far to truncate a timestamp for each releasable bucket.
_BUCKET_CHARS = {"year": 4, "quarter": 7, "month": 7, "day": 10}


def _describe_body(profile: Profile) -> str:
    """Emit one accumulation line per leaf, at the resolution it may be released.

    An aggregate-only field is coarsened here rather than reported raw: a
    HIGH_LEVEL timestamp releasable as a month must never leave the function as
    a timestamp, and a template that emits one is not enforcing the policy it
    claims to.
    """
    lines = []
    for leaf in profile.all_leaves():
        expr = accessor(leaf.path)
        if leaf.is_numeric:
            lines.append('        numeric["{0}"].append(_number({1}))'.format(
                leaf.path, expr))
        elif leaf.is_temporal and not leaf.is_detailed:
            bucket = (leaf.releasable_as or ["year"])[-1]
            width = _BUCKET_CHARS.get(bucket, 4)
            lines.append(
                '        totals["{0}"][_bucket({1}, {2})] += 1'
                '  # {3}, per the profile'.format(leaf.path, expr, width, bucket))
        else:
            lines.append('        totals["{0}"][str({1})] += 1'.format(
                leaf.path, expr))
    lines.append("")
    return "\n".join(lines)


def _logistic_body(covariates: List[str]) -> str:
    lines = []
    for path in covariates:
        lines.append('        strata[("{0}", str({1}))][outcome] += 1'.format(path, accessor(path)))
    lines.append("")
    return "\n".join(lines)


_NUMBER_HELPER = '''
def _number(value):
    """Coerce a CSV field to a number, or None when it is not one."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return None

'''


def render(profile: Profile, match: Match, chart: bool = False) -> str:
    """Render the analysis code for a feasible match.

    With chart=True the module also gains a chart() that draws the *released*
    result -- the same suppressed aggregate main() returns. A figure drawn from
    records rather than from the released table is a disclosure risk that no
    output review can see, so the generator never offers that shape.
    """
    if not match.feasible:
        raise SnippetError(
            "{0} is not feasible for this dataset: {1}".format(
                match.key, match.blockers[0] if match.blockers else "unknown reason"))
    template = _TEMPLATES.get(match.key)
    if template is None:
        raise SnippetError("no template for analysis '{0}'".format(match.key))

    card_ref = profile.schema_hash[:12] if profile.schema_hash else (profile.archetype_id or "measured locally")
    values = {
        "title": match.title,
        "summary": match.summary,
        "unit": match.unit,
        "unit_note": _unit_note(profile, match),
        "caveat_block": _caveat_block(match),
        "card_ref": card_ref,
        "min_cell": str(profile.min_cell),
    }

    body = _HEADER
    params = match.params

    if match.key == "describe":
        body += _NUMBER_HELPER + _SUPPRESS
        values["describe_body"] = _describe_body(profile)
    elif match.key == "composition":
        values["outcome_expr"] = accessor(params["outcome"])
        values["by_expr"] = accessor(params["by"])
        values["outcome_name"] = _slug(params["outcome"])
        values["by_name"] = _slug(params["by"])
    elif match.key == "cross_tab":
        values["rows_expr"] = accessor(params["rows"])
        values["cols_expr"] = accessor(params["cols"])
        values["rows_name"] = _slug(params["rows"])
        values["cols_name"] = _slug(params["cols"])
    elif match.key == "prevalence":
        if not profile.grain.dedupe_key:
            raise SnippetError("prevalence requires a dedupe key")
        body = body.replace("MIN_CELL = $min_cell", 'POSITIVE = set()  # fill in the values that count as positive\nMIN_CELL = $min_cell')
        values["dedupe_expr"] = accessor(profile.grain.dedupe_key)
        values["outcome_expr"] = accessor(params["outcome"])
    elif match.key == "group_compare":
        values["value_expr"] = accessor(params["value"])
        values["group_expr"] = accessor(params["group"])
    elif match.key == "logistic":
        body = body.replace("MIN_CELL = $min_cell", 'POSITIVE = set()  # fill in the values that count as positive\nMIN_CELL = $min_cell')
        covariates = [c.strip() for c in params.get("covariates", "").split(",") if c.strip()]
        values["outcome_expr"] = accessor(params["outcome"])
        values["outcome_name"] = params["outcome"]
        values["logistic_body"] = _logistic_body(covariates)
    elif match.key == "trend":
        bucket = (params.get("buckets") or "year").split(",")[0].strip()
        width, note = _BUCKET_WIDTH.get(bucket, _BUCKET_WIDTH["year"])
        values["time_expr"] = accessor(params["time"])
        values["bucket_width"] = str(width)
        values["bucket_note"] = note
        values["bucket_label"] = bucket

    section = _CHART_SECTIONS.get(match.key) if chart else None
    if chart and section is None:
        raise SnippetError(
            "'{0}' has no chart: it returns a single figure rather than a "
            "table. Chartable analyses: {1}.".format(
                match.key, ", ".join(sorted(_CHART_SECTIONS))))
    if section:
        body = body.replace("from generated.models import create_dataset",
                            "from generated.models import create_dataset\n"
                            + _CHART_IMPORT.rstrip())
        template = template.replace(
            '''if __name__ == "__main__":''',
            section.strip() + '''\n\nif __name__ == "__main__":''')
        template = template.replace(
            "print(json.dumps(main(), indent=2, default=str))",
            "print(json.dumps(main(), indent=2, default=str))\n"
            "    print(\"chart written to\", chart())")
        values["chart_path"] = "{0}.svg".format(match.key)
        values["chart_title"] = _chart_title(match)

    return Template(body + template).safe_substitute(values)


def _chart_title(match: Match) -> str:
    params = match.params
    if match.key == "cross_tab":
        return "{0} by {1}".format(params.get("rows", ""), params.get("cols", ""))
    if match.key == "composition":
        return "{0} by {1}".format(params.get("outcome", ""), params.get("by", ""))
    return match.title


def write(profile: Profile, match: Match, project_dir: str = ".",
          filename: Optional[str] = None, chart: bool = False) -> str:
    """Render a snippet and write it under analyses/. Returns the path."""
    code = render(profile, match, chart=chart)
    directory = os.path.join(project_dir, ANALYSES_DIR)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    init_path = os.path.join(directory, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w", encoding="utf-8") as fh:
            fh.write("")
    # Snippets always land directly in analyses/. Callers -- an agent among
    # them -- routinely pass "analyses/foo.py", which would otherwise nest a
    # second analyses/ and fail on the missing directory.
    name = os.path.basename(filename or "{0}.py".format(match.key))
    if not name:
        raise SnippetError("filename is empty")
    if not name.endswith(".py"):
        name += ".py"
    if chart:
        helper = os.path.join(directory, CHART_HELPER_NAME)
        if not os.path.exists(helper):
            with open(helper, "w", encoding="utf-8") as fh:
                fh.write(CHART_MODULE)

    path = os.path.join(directory, name)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(code)
    return path
